### ISSUE TITLE
React Hot Loader 2 Umbrella

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-hot-loader#186]
- [x] Use [React Proxy](https://github.com/gaearon/react-proxy) as new internal engine
- [x] Support hot-reloading getters, statics (via React Proxy)
- [x] Remove dependency on `react/lib/ReactMount`
- [x] Recover from module definition level errors
- [x] Recover from file not found errors
- [ ] Show syntax errors in an overlay (maybe even switch to [webpack-hot-middleware](https://github.com/glenjamin/webpack-hot-middleware) by @glenjamin)
- [ ] Recommend using [babel-plugin-wrap-react-components](https://github.com/gaearon/babel-plugin-wrap-react-components) for a better experience:
  * [ ] Hot-reload non-exported classes
  * [ ] Hot-reload classes that are wrapped in HOCs
  * [ ] Take another look at hot reloading ES7 properties
  * [ ] Make it easy to handle `render()` errors (https://github.com/gaearon/react-hot-loader/issues/164)
- [ ] Keep the old export rewriting for CoffeeScript and other compile-to-JS users?
- [ ] Make sure stuff like Omniscient still works

**Comment by glenjamin** [comment]
It seeks like perhaps these
>Show syntax errors in an overlay (maybe even switch to webpack-hot-middleware by @glenjamin)
> Recover from module definition level errors
> Recover from file not found errors

Should be out of scope for RHL, as they're not react specific? Maybe just include suggested approaches in docs?

Afaik, hot-middleware handles all 3 cases currently.

**Comment by STRML** [comment]
Depending on a shared module that handles syntax errors/ENOENT sounds like the right approach to me. :+1:

**Comment by gaearon** [comment]
>Maybe just include suggested approaches in docs?

Yes, that's what I meant. I mean not just the code, but also the boilerplate, Getting Started guide, etc.

**Comment by gaearon** [comment]
@glenjamin 

Though as you probably saw, 

>Recover from module definition level errors

and

>Recover from file not found errors

(when `NoErrorsPlugin` isn't enabled)

were actually broken until #187 so that counts.

**Comment by gaearon** [comment]
Meh, this is very old.
